name: Continuous Integration

on: push

jobs:
  open-api-tests:
    name: Open API Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # When all tests are consistently passing this should be turned off
      matrix:
        go: [ 1.14, 1.15 ]
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Go ${{ matrix.go }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - name: Start Prism # This is a workaround as Github Actions does not currently support passing a command to a service container
        run: docker run -d -p 4010:4010 stoplight/prism:3 mock -h 0.0.0.0 https://bitbucket.org/api/swagger.json
      - name: Wait for Prism to start
        run: sleep 30s
      - name: Run tests
        run: make open-api-test
